### ISSUE TITLE
Funcionalidad 3: Encuestas

### ISSUE THREAD

**Issue by JustAntoRS** [acmfi/discord-bot#11]
Implementar un sistema de encuestas con generacion de gráficos basicos. 
Tareas a realizar para encuesta múltiple:
- [x] El usuario envia un comando con la pregunta y las opciones para crear nueva encuesta
- [X] El bot responde con un mensaje por el canal con la pregunta y las opciones enumeradas
- [X] El bot reacciona a su propio mensaje con los emojis del 1 a N, siendo N el número de opciones que hay en la encuesta
- [X] Se podrá realizar una encuesta solo con respuesta Si/No si el usuario solo añade una pregunta sin opciones. Se usarán los emojis del tick(✔️) o de la aspa(❌ )
- [x] No se permitirá añadir nuevas reacciones a los usuarios
- [x] Se debe meter un temporizador con un valor de defecto a 1 minuto. El usuario que crea la encuesta podrá editar el tiempo.
- [x] Una vez el tiempo llega a su fin, se muestra un mensaje de fin.
- [X] ~~Se envia un gráfico con el porcentaje de las respuestas~~ Será implementada en versión futura

**Comment by onmax** [comment]
[Link a la rama](https://github.com/acmfi/discord-bot/tree/issue_3-polls)

**Comment by onmax** [comment]
Alguna solución para esto? 
https://github.com/acmfi/discord-bot/commit/441713fade28e8bdbf763b0b2bbbf59b6c1f773d#r42459460
