### ISSUE TITLE
Funcionalidad 9: Creacion canales de texto dinamicamente

### ISSUE THREAD

**Issue by JustAntoRS** [acmfi/discord-bot#16]
Dotar a los canales de voz de un canal escrito exclusivo mediante canales de texto que aparecen solo a los integrantes de ese canal de voz, así si tienen que escribir algo no hay que usar un canal de texto global, como el hemiciclo 1003, que si hay más de un grupo a la vez se pueden mezclar mensajes, y si todos los chats de voz tienen su correspondiente chat de texto visible sería todo demasiado largo para encontrar cualquier cosa.

**Comment by Formil** [comment]
Implementando un poco esta funcionalidad me surgen algunas dudas que creo que estaría bien solventar para cualquiera que se ponga con ello:
(Asumo que los canales son los mismos siempre para guardar los mensajes como se habló)
¿Todos los canales tendrán esta funcionalidad?¿Qué canal de texto relacionamos con cada canal de voz? ¿Alguno de los que están ya creados en el servidor o serían otros canales nuevos? Si es otros nuevos ¿Debería crearlos el bot, o estarán ya creados?

Básicamente lo digo por saber como relacionarlos, si hacer que se active el canal que tenga el mismo nombre que al canal de voz que al que se une (o alguna variación de este), o tener un diccionario con el nombre del canal de texto correspondiente a cada uno de los de voz, o si hace falta que, si no existe ninguno relacionado, el bot cree otro y lo relacione.

No sé si me explico ni si serán preguntas tontas, pero es lo que me gustaría saber.

**Comment by Santixs** [comment]
Creo que si deben ser los mismos canales para que se puedan guardar los mensajes, respecto a que canales, yo lo haría con todos, en cualquier canal puede darse la situación de que haya que escribir algo.

Para mi lo mas intuitivo sería que fueran nuevos canales que se llamaran igual que los de voz pero con “-texto” o algo así y estuviera cada uno justo debajo del correspondiente chat de voz.

Mas que crearlos el bot creo que lo mejor sería (aunque no se si se puede) que el bot los mostrara/ocultara a los participantes que estan en el canal de voz, pero los canales en sí no se borraran nunca.

**Comment by Formil** [comment]
He abierto la branch #16 he subido un código sobre esta funcionalidad. No creo que sea demasiado eficiente, pero ya que (al menos en mi servidor de prueba) me ha funcionado, quizás a otros les vale para empezar.

**Comment by JustAntoRS** [comment]
La primera PR de esta funcionalidad ha sido mergeada, cierro.
