### ISSUE TITLE
Tools to create Discord bots

### ISSUE THREAD

**Issue by JustAntoRS** [acmfi/discord-bot#2]
What has been enabled to create bots? 

Post link to library and short description about it (pls) :)

**Comment by jonsalchichonnn** [comment]
librería discord.py

https://discordpy.readthedocs.io/en/latest/index.html

https://discordpy.readthedocs.io/en/latest/quickstart.html

https://www.devdungeon.com/content/make-discord-bot-python#install_python_package

**Comment by Thurmiel** [comment]
DiscordBots with Java, Python , JS or C# : https://www.writebots.com/how-to-make-a-discord-bot/

**Comment by JustAntoRS** [comment]
> DiscordBots with Java, Python , JS or C# : https://www.writebots.com/how-to-make-a-discord-bot/

JS is not going to happen :)

**Comment by Thurmiel** [comment]
I like that :)

**Comment by onmax** [comment]
And TS?

**Comment by JustAntoRS** [comment]
> 
> 
> And TS?

Podriamos estudiarlo, el unico NO rotundo es JS xD

**Comment by JustAntoRS** [comment]
Si no queremos usar ningun framework para crear bots de Discord tambien podemos usar alguna libreria que haga request http (que yo sepa, la gran mayoria de lenguajes de programacion tiene una) ya que Discord tiene una API http/rest y parece bien documentada https://discord.com/developers/docs/reference

**Comment by Thurmiel** [comment]
Puede que nos sirva para integrarlo con telegram, lo he mirado muy poco https://www.integromat.com

**Comment by JustAntoRS** [comment]
Hemos elegido Python como lenguaje debido a que varios miembros querian aprenderlo y entre los propuestos es el que tiene una curva de aprendizaje mas sencilla.

**Comment by onmax** [comment]
Librería para trabajar con eventos asíncronos: [https://github.com/ReactiveX/RxPY](RxPY)

**Comment by skgsergio** [comment]
Prfff Python, pensaba que en ACM solo se usaban true lenguajes de programación como OCaml, Haskell o apurando mucho Elixir.

**Comment by samgh96** [comment]
Aquí @skgsergio tiene razón, por eso hay que hacer votación para echarle de la asociación

**Comment by onmax** [comment]
Casi cogemos JS para fastidiar a la gente de ACM, pero al final no 😄
