### ISSUE TITLE
Crear fichero para datos

### ISSUE THREAD

**Issue by JustAntoRS** [acmfi/discord-bot#27]
Craer un fichero con la variable PERMITTED_ROLE_NAME con la funcion para importarlo cuando se necesite.

**Comment by JustAntoRS** [comment]
TOKEN = ""

**Comment by Daniel-Tomas** [comment]
Fichero de variables de Python. Jason no

**Comment by onmax** [comment]
También habría que poner la variable para el prefijo del comando

**Comment by JustAntoRS** [comment]
Se discutio y se decidio crear 2 ficheros, un .json para variables de configuracion del bot (token, por ejemplo) y un fichero .py para variables que no son de configuracion pero si que son de uso comun para 2 o mas funcionalidades.
