### ISSUE TITLE
Discutir el nombre de la arquitectura que vamos a usar

### ISSUE THREAD

**Issue by JustAntoRS** [acmfi/discord-bot#29]
Haz un comentario con el nombre y que la gente lo vote

**Comment by JustAntoRS** [comment]
Esto se ha discutido y se ha decidido ya si no recuerdo mal, @onmax podrias poner aqui un resumen o algo de la arquitectura y asi cerramos la issue??

**Comment by onmax** [comment]
Hola, he estado pensando una posible solución a la estructura del proyecto. La estructura general que tengo pensada es la siguiente:
```
proyect
├── .git
├── .gitignore
├── .env
├── Dockerfile
├── src
│    ├── bot.py
│    ├── api
│    │    └── ...
│    ├── extensions
│    │        ├── views
│    │        │    ├── poll.py
│    │        │    └── ...
│    │        └── logic
│    │             │── lib
│    │             │     ├── command.py
│    │             │     ├── other_common_classes.py
│    │             │     └── ...
│    │             │── poll
│    │             │      │── poll_command.py
│    │             │      │── poll_handler.py
│    │             │      └── ...
│    │             └── ban_hammer
│    │                    │── ban_hammer.py
│    │                    └── ...
│    └── static
│            └── data.json
└── test
         └── ...
```

Que os parece? Alguna sugerencia de cambio?

**Comment by xiaopeng-ye** [comment]
A mi parece bien

**Comment by JustAntoRS** [comment]
Okay, creo que hay consenso en general. Creo una issue para hacer tracking de esto y reordenar lo que hay ahora mismo en `master` siguiendo la estructura definida.

Me pongo yo como asignee y me encargo de ello para mañana (Martes, 15 de Septiembre)
