### ISSUE TITLE
Bot functionalities

### ISSUE THREAD

**Issue by JustAntoRS** [acmfi/discord-bot#3]
Write here what you think could be a cool feature for the bot or something the Discord server could beenefit from

**Comment by JustAntoRS** [comment]
1. Integración con Telegram para que al enviar un mensaje por el canal de anuncios de ACM UPM en Telegram, este mismo mensaje se envie automaticamente por el canal de texto de anuncios de Discord

**Comment by JustAntoRS** [comment]
2. Sistema de control de voz para las charlas, solo necesario en los canales de voz y texto "hemiciclo 1003"

Pensar en un sistema para levantar la mano o algo por el estilo (no lo tengo claro)

**Comment by JustAntoRS** [comment]
3. (Propuesta durante la primera reunion, realizada el Viernes 24 de Julio)

Implementar un sistema de encuestas con generacion de gráficos basicos.

**Comment by JustAntoRS** [comment]
4. (Propuesta durante la primera reunion, realizada el Viernes 24 de Julio)

Debido a que ACM somos una organizacion "grande" y el link que ahora mismo estamos usando para que la gente se una al canal de Discord es un link permanente, podria ocurrir que alguien son raideara (gente que no forma parte de ACM se una al servidor para trollear/molestar) 

Para evitar esto y no tener que estar generando un link nuevo cada vez que alguien se quiera unir....

Podemos diseñar un sistema de proteccion donde cuando entras al servidor se te haga una pregunta y en base a la respuesta te deje entrar o no.

Este sistema se puede mejorar su diseño e implementacion y hacer cosas muy chulas.

Author: @Santixs

**Comment by Thurmiel** [comment]
5. Un calendario o similar con las charlas y eventos que se organizan desde ACM

**Comment by Formil** [comment]
6. Relacionado con el calendario, complementarlo con comandos de información sobre los eventos y charlas (título,fecha, hora, ponente,link si hay al post en la página de acm) , por ejemplo uno que te diga sobre los de la semana o el mes en el que estás, o que te proporcione la información sobre el siguiente.

**Comment by JustAntoRS** [comment]
>     1. Un calendario o similar con las charlas y eventos que se organizan desde ACM

Mola la idea, y el añadido de @Formil tambien. Ya usamos un [calendario](https://upm.acm.org/wp/calendario/) asi que seria mas estudiar como integrar Google Calendar y diseñar la integracion.

**Comment by FORGIS98** [comment]
7. Bot que **añada y quite roles automaticamente**. Sobre todo para cuando demos charlas en el H-1003. Por que se nos va a olvidar quitar el rol de "ponente" 100% seguro (ya nos ha pasado 1 vez).

8. También para miembros nuevos poder **enviar un mensaje de bienvenida automatico** con algo de info sobre ACM y demas redes sociales por si aca :D y/o (no se si discord lo tiene integrado) pero **programar mensajes** y que se envien X día a X hora.

**Comment by Santixs** [comment]
9.Dotar a los canales de voz de un canal escrito exclusivo mediante  canales de texto que aparecen solo a los integrantes de ese canal de voz, así si tienen que escribir algo no hay que usar un canal de texto global, como el hemiciclo 1003, que si hay más de un grupo a la vez se pueden mezclar mensajes, y si todos los chats de voz tienen su correspondiente chat de texto visible sería todo demasiado largo para encontrar cualquier cosa.

10. Sistema de moderación automática, que cambie palabras extremadamente ofensivas por equivalentes no ofensivos (¿y con un toque cómico/irónico?)

**Comment by JustAntoRS** [comment]
>     1. Bot que **añada y quite roles automaticamente**. Sobre todo para cuando demos charlas en el H-1003. Por que se nos va a olvidar quitar el rol de "ponente" 100% seguro (ya nos ha pasado 1 vez).
> 
>     2. También para miembros nuevos poder **enviar un mensaje de bienvenida automatico** con algo de info sobre ACM y demas redes sociales por si aca :D y/o (no se si discord lo tiene integrado) pero **programar mensajes** y que se envien X día a X hora.

Creo que el punto 8 lo hace automaticamente Discord (creo, tendria que confirmarlo y ver si se puede personalizar ese mensaje)

**Comment by JustAntoRS** [comment]
Creo que 10 esta bien para empezar, si tenemos mas al principio igual se nos hace bola. Mejor empezar con estas 10 y durante el desarrollo ir viendo como avanzamos.
